module.exports = {
	//plugins: ['prettier-plugin-tailwindcss'],
	useTabs: true,
	tabWidth: 2,
	semi: false,
	singleQuote: true,
	trailingComma: 'all',
	printWidth: 80,
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: 'avoid',
	proseWrap: 'preserve',
	htmlWhitespaceSensitivity: 'css',
	endOfLine: 'lf',
}
